### ISSUE TITLE
Update for v0.5 of framework

### ISSUE THREAD

**Issue by amygroshek** [cgkineo/adapt-tabs#19]
AT version: 0.10.3
Framework version: 0.5.4
Theme: vanilla

The following error results when attempting to export or publish a course.

```
Command failed: grunt server-build:prod --outputdir=courses/5ebc1dbb7268623938f00056/5ebd1f239d6ed208d7c6c966/build --theme=5ebc20e06ab31b39cd1c8661 --menu=adapt-contrib-boxMenu

Fatal error: {
 "message": "variable @item-text-color is undefined",
 "type": "Name",
 "filename": "src/components/adapt-tabs/less/tabs.less",
 "index": 329,
 "line": 21,
 "column": 9,
 "callLine": null,
 "extract": [
  "\t\tborder-radius: 20px 0 0 20px;",
  "\t\tcolor: @item-text-color;",
  "\t\tdisplay: block;"
 ]
}
```

**Comment by moloko** [comment]
Could you give https://github.com/cgkineo/adapt-tabs/tree/release/v5 a try and let us know if OK?

**Comment by amygroshek** [comment]
@moloko Dang, missed that. Yup, it works when I test with the v5 release. :)

**Comment by moloko** [comment]
no problem. it wasn't exactly obvious. If you wouldn't mind, could you add a `+1` comment to #18 with a comment saying you've tried it out?
