### ISSUE TITLE
Navigation tab-order and DOM order of content vs. navigation

### ISSUE THREAD

**Issue by sebastian-onlea** [cgkineo/adapt-tabs#24]
I'm looking into why the keyboard navigation tab order is somewhat counterintuitive - the tab navigation elements are visually placed before (above/left of) the tab content divs, but come _after_ the content in the DOM order, so any hyperlinks (or other tab-navigable elements) in the content of a tab will come before the navigation tabs in the tab order.

Moving the tabs after the content appears to have been a [deliberate change](https://github.com/cgkineo/adapt-tabs/commit/7f47016f04aed83b0e4d87fe53dd12963fd0d240#diff-838af3c55cd9de9acfd5cb22c59503745370b91457047d6711839e3cc1678674) but there's no specific mention of it in the commit or the comments. Can anyone (@guywillis?) fill me in on the problem for which this is the solution, and any potential unintended consequences of re-ordering the DOM to get the tab order to match the visual flow of the component?

cheers!

**Comment by oliverfoster** [comment]
Well.... If the tabs are above the content, when the screen reader cursor goes through the elements, it hits the buttons, jumps to the content and then the user carries on without any indication that there are more elements to complete.

When the tabs are beneath the content, the screen reader cursor goes through the content, onto the tabs, bounces up to the next bit of content and then back to the tabs, etc, until the user progresses of their own accord having completed everything.

**Comment by sebastian-onlea** [comment]
Ah, I see - that's interesting, and makes sense. I've not seen that approach in any tab-navigation accessibility best-practices guides before.

**Comment by oliverfoster** [comment]
It's just a small change to aid cognition and keep the number of navigational strokes down.

Can I close this issue?

**Comment by sebastian-onlea** [comment]
I'm still personally bumping on the inconsistency in visual flow vs. the navigational sequencing benefits you mention. Would it make sense to move the tabs visually "after" the content (to the bottom/right) so that it's consistent with the tab ordering, or include that as a presentation option for the component? I can put together a PR.

**Comment by oliverfoster** [comment]
This is an intentional design to aid screen reader users, yes the order is wrong but it is intentionally so. 

You should be able to override the styling to put them at the bottom in your own theme / course.

**Comment by sebastian-onlea** [comment]
> You should be able to override the styling to put them at the bottom in your own theme / course.

Alright. We'll take that approach, thanks.
