### ISSUE TITLE
JAWS reads all content as if one block of text

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-tabs#25]
JAWS will read out the content of the first tab, then immediately read out the contents of all subsequent tabs straight after it (as if it was being displayed as one block of text). After that, it moves onto the next tab, and will do the same thing, except this time minus the content of the first tab. This carries on for all tabs - for example, if the component contains three tabs, the reading order will be:

- Tab 1 header
- Tab 1, 2, and 3 text
- Tab 2 header
- Tab 2 and 3 text
- Tab 3 header
- Tab 3 text

Tested in Chrome / JAWS 2021.

**Comment by simondate** [comment]
My client have been performing Accessiblity testing in Adapt and have noticed this too

https://imgur.com/a/DpMuS3G

Plugin version 3.0.1
FW version 5.12.2

From the Testers report -

> Tester has observed that when navigating through the page with iOS VoiceOver and Android TalkBack, the focus order is not logical. It is expected that the navigation order of the page is logical and consistent.
> 
> For example, when navigating through the the page with Android TalkBack enabled, the user is focused on the visually hidden ‘hint’ content when the button has not been interacted with. Furthermore, when navigating with both Android TalkBack and iOS VoiceOver, the user is focused on content that is not visually present within the ‘Stacklist’, ‘Flipcard’, ‘Tabs’ and ‘Open Text Input’ components. Please see attached evidence for further details.
> 
> This does not comply with WCAG Level A 2.1:
> 2.4.3 Focus Order - https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html
> 
> Steps to Recreate:
> 1. Navigate to URL
> 2. Swipe the page content with Android TalkBack and iso VoiceOver enabled
> 3. Observe issues

**Comment by oliverfoster** [comment]
please use v4, which requires fw version 5.14 

https://github.com/cgkineo/adapt-tabs/tree/v4.0.0
