### ISSUE TITLE
2 issues make the adapt-tabs build fail

### ISSUE THREAD

**Issue by samumist** [cgkineo/adapt-tabs#3]
1. on line 204 in the `less/tabs.less`, `@theme-black` is not defined.
2. on line 38 in the `properties.schema`, the `"validators": [required]` , cause the build fail.

**Comment by guywillis** [comment]
Hi Samumist,

Thanks for your feedback.

I have updated the variable to use 'background-color-inverted' and added the missing quotes on line 38 to hopefully resolve this build failure. 

Could you let me know if this has resolved the build failures you are experiencing?

**Comment by samumist** [comment]
Yes, the problem is resolved.

Many thanks
