### ISSUE TITLE
Align with WCAG guildlines (move focus to tab panel)

### ISSUE THREAD

**Issue by RMurray89** [cgkineo/adapt-tabs#32]
When I tab to a tabs component, focus is on first tab. You can then use arrow keys to move left/ right. Pressing return or space visually opens the tabpanel, but does not move keyboard focus. You can disable forms mode, but that still means tabbing through any content to the right of the active tab.

I've been reading about the correct use of the aria tabs/ tabpanel role and it's suggested that the tab controls should not receive tab focus once the 1st tab is active. Once inside the list of tabs, left and right keys are the only controls for moving focus. Selecting would then place focus onto the tab panel automatically (it's suggested tabindex="0" on that tabpanel can help with this). Another option would be to allow down arrow to move focus to the content. Shift tab moves back to the tab list/ current tab. I think down arrow into the tabpanel is preferred over tab as tab would automatically go to the first focussable element (i.e. if there was a link in the tabpanel content).

I like how this tabpanel behaves https://inclusive-components.design/tabbed-interfaces/ - which seems to work well as an example

Although I don't think this is user error (I've tried several ways to access the content) - I'm happy to be shown otherwise.  

The headings shortcut (H) key could in my testing does move you into the tabpanel once selected, but not ideal user experience.

**Comment by RMurray89** [comment]
Example tabs in a demo course

[tabs-demo-test.zip](https://github.com/cgkineo/adapt-tabs/files/8488061/tabs-demo-test.zip)

**Comment by oliverfoster** [comment]
See thread https://community.adaptlearning.org/mod/forum/discuss.php?d=4126

Agreed on this example https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

It seems to need a tabindex on the tabpanel and an appropriate call to a11y.focus somewhere.

**Comment by RMurray89** [comment]
Hi @oliverfoster - Just wondering if you can provide an indication of the timescale on this one? An assistive tech user has flagged it in testing. I was aware of the issue before the user flagged it and think if we need to we can hopefully get around by elaborating on the instructional text, although not ideal!
