### ISSUE TITLE
Account for xlarge screensize

### ISSUE THREAD

**Issue by hanshillen** [cgkineo/adapt-tabs#40]
The tabs layout is only set to horizontal when `device.screenSize` is `large`.

Since `xlarge` was added to the schema, the tabs will always be vertical at this size regardless of configuration

**Comment by oliverfoster** [comment]
Which version are you using?

**Comment by hanshillen** [comment]
4.0.5

**Comment by oliverfoster** [comment]
schema https://github.com/cgkineo/adapt-tabs/blob/5c8914e5a0059397a9db7cc08a04da7dd1bf016c/properties.schema#L46-L55

example https://github.com/cgkineo/adapt-tabs/blob/5c8914e5a0059397a9db7cc08a04da7dd1bf016c/example.json#L13

less https://github.com/cgkineo/adapt-tabs/blob/5c8914e5a0059397a9db7cc08a04da7dd1bf016c/less/tabs.less#L1-L39

view https://github.com/cgkineo/adapt-tabs/blob/5c8914e5a0059397a9db7cc08a04da7dd1bf016c/js/TabsView.js#L8-L20

isScreenSizeMin https://github.com/adaptlearning/adapt-contrib-core/blob/de6fcd9c58ad7ed0d793920b048fcb213bdcc980/js/device.js#L80-L82

I find it really difficult to see how you're getting different results. My first suspect was isScreenSizeMin in the view layout function but that just uses css media queries from the large size.

Can you please post your [`config.json:screenSizes`](https://github.com/adaptlearning/adapt-contrib-core/blob/de6fcd9c58ad7ed0d793920b048fcb213bdcc980/js/device.js#L59) configuration, src/js/core:package.json version number and the configuration of the component?

**Comment by hanshillen** [comment]
Yeah my version of TabsView.js is different, line 16 reads `const layout = (device.screenSize === 'large')`. 

I was getting an older release through adapt cli, the current issue can be closed

**Comment by oliverfoster** [comment]
You're right, 4.0.5 is old code. This needs releasing again.

**Comment by oliverfoster** [comment]
v4.0.6 should be fixed, thanks for reporting :+1:
