### ISSUE TITLE
Use in Authoring Tool?

### ISSUE THREAD

**Issue by hbaileylxd** [cgkineo/adapt-tabs#5]
Hi guys,

I tried this out on AT 0.1.4 and it goes great but when I preview I get the spinning loading wheel of death on the page it's on. Is it just not suited to the AT or is there something that can be tweaked to make it work? Nothing reported in the Command Prompt.

Cheers :)

**Comment by moloko** [comment]
probably something not quite right in the .json - if you can add here the relevant bit of .json that the authoring tool creates one of us will have a look

**Comment by hbaileylxd** [comment]
cheers... lemme find it. (Hope this is the right bit? - from components.json?)

``` json
  {
    "_id": "5656db0a5e1cf324102845a7",
    "_parentId": "5656da665e1cf324102845a6",
    "_type": "component",
    "_layout": "full",
    "body": "<p>Testing Tabs</p>\n",
    "displayTitle": "Test Tabs",
    "title": "Test Tabs",
    "_isOptional": false,
    "_classes": "",
    "_component": "tabs",
    "_items": [
      {
        "_graphic": {
          "src": "",
          "alt": ""
        },
        "body": "<p>Testing Tabs</p>\n",
        "title": "Testing Tabs",
        "tabTitle": "Testing Tabs"
      },
      {
        "_graphic": {
          "src": "",
          "alt": ""
        },
        "body": "<p>Testing Tabs 2</p>\n",
        "title": "Testing Tabs 2",
        "tabTitle": "Testing Tabs 2"
      }
    ],
    "_tabLayout": "left",
    "instruction": ""
 }
```

**Comment by moloko** [comment]
@hmaffin sorry about the delay in looking at this, I haven't forgotten though - just been busy with project work!

**Comment by moloko** [comment]
Right, first off I'm _very_ embarrassed as to how long it has taken me to get around to looking at this - sorry @hmaffin!

I've just given this a try myself, just by using the out-of-the-box version of the framework (v2.0.6, specifically) and the example.json from this repository - and immediately encountered #6 which I _think_ might be the source of your problem. 

I hacked in a workaround for that, made sure that was working and then switched over to the sample .json you posted above, whereupon I got this:
![2016-01-18 20_01_05-adapt version 2 0 demonstration _ presentation components](https://cloud.githubusercontent.com/assets/1249597/12401453/559f85e4-be1e-11e5-85f4-aa3d6e3a7d64.png)
So it is basically working, the stray bit of `tabindex` stuff is down to the fact that you haven't included tab graphics, but the AT is spitting out empty properties for `_graphic.src` and `_graphic.alt` which then aren't being handled properly - this needs to be fixed either with changes to the [properties.schema](../blob/master/properties.schema) or with updates to [tabs.hbs](../blob/master/templates/tabs.hbs)

**Comment by hbaileylxd** [comment]
OK - just tried it again in the AT and can put everything in ok but still spinning wheel of death on the page. Can I hack it someway - take out any reference to component-margin-bottom perhaps?

**Comment by moloko** [comment]
should all be working now, thanks for your patience
