### ISSUE TITLE
tabs.less uses variable @component-margin-bottom which doesn't exist in Adapt

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-tabs#6]
both `.tab-content-item-title` and `.tab-content-item-body` use the variable `@component-margin-bottom` which causes the compiler to throw the error `variable @component-margin-bottom is undefined`

I think these classes should be using `@component-title-margin-bottom` and `@component-body-margin-bottom` respectively?

**Comment by hbaileylxd** [comment]
Woop! I changed these and it works!!!!

Great one Moloko!

**Comment by moloko** [comment]
I'm actually right in the middle of making this change so good to know it will definitely work

**Comment by moloko** [comment]
should all be sorted now
