### ISSUE TITLE
URL in content causes focus shift

### ISSUE THREAD

**Issue by robmausser** [cgkineo/adapt-tabs#9]
If you put a URL in the content, specifically in an area that you have to scroll to, the tab section will load and then automatically scroll to that area, highlighting the URL.

**Comment by moloko** [comment]
IIRC it's actually the accessibility library in Adapt that's doing this, I'll have to do a bit of digging to find out what the fix is. In the meantime, it would help to know whether you actually need accessibility on your project or not?

**Comment by robmausser** [comment]
Yes it's required very much so. Full wcag 3.0
